const cloud = require('wx-server-sdk')
cloud.init({ env: cloud.DYNAMIC_CURRENT_ENV })
const db = cloud.database()
const _ = db.command

const BEIJING_OFFSET = 8 * 60 * 60 * 1000

// ===== 北京时间工具函数（与 getInsights、prefetchData 保持同步） =====

// 将 Date 对象转为北京时间日期字符串 YYYY-MM-DD
function formatDateStr(d) {
  const local = new Date(d.getTime() + BEIJING_OFFSET)
  return local.getUTCFullYear() + '-' + String(local.getUTCMonth() + 1).padStart(2, '0') + '-' + String(local.getUTCDate()).padStart(2, '0')
}

// 北京时间 dateStr 的 00:00:00 → 对应的 UTC Date 对象
function beijingStart(dateStr) {
  return new Date(new Date(dateStr + 'T00:00:00').getTime() - BEIJING_OFFSET)
}

// 北京时间 dateStr 的 23:59:59.999 → 对应的 UTC Date 对象
function beijingEnd(dateStr) {
  return new Date(new Date(dateStr + 'T23:59:59.999').getTime() - BEIJING_OFFSET)
}

/**
 * Daily timer — auto create banquet purchase & income for reservations on today's date.
 * Also backfills past 3 days as a safety net.
 * Cleans up purchase/income for cancelled reservations.
 * Skips reservations that already have linked records.
 */
exports.main = async (event, context) => {
  try {
    // 1. Load needed settings precisely (including approval_rules in single query)
    const neededKeys = ['serviceChargeEnabled', 'serviceChargeEnabledDate', 'serviceChargeNoon', 'serviceChargeNight', 'approval_rules']
    const settingsRes = await db.collection('settings').where({ key: _.in(neededKeys) }).get()
    const settings = {}
    ;(settingsRes.data || []).forEach(s => {
      if (!(s.key in settings)) {
        // approval_rules stores fields at top level (no .value), other settings use .value
        settings[s.key] = s.key === 'approval_rules' ? s : (s.value !== undefined ? s.value : s)
      }
    })

    // 先解析 autoSyncMode（兼容老字段 autoPurchaseEnabled）
    var rawRules0 = settings.approval_rules || {}
    var autoSyncMode = rawRules0.autoSyncMode
    if (!autoSyncMode) {
      autoSyncMode = rawRules0.autoPurchaseEnabled === false ? 'none' : 'purchase_and_income'
    }

    if (autoSyncMode === 'none') {
      console.log('[autoSync] 自动同步已关闭，跳过')
      return { skipped: true, reason: 'autoSyncMode none' }
    }

    // purchase_and_income 和 purchase_only 依赖 dishPrice，需服务费模式
    // income_only 在服务费模式关闭时按单价模式自动算收入
    const serviceChargeEnabled = !!settings.serviceChargeEnabled
    if (!serviceChargeEnabled && autoSyncMode !== 'income_only') {
      console.log('[autoSync] 服务费模式未开启且非 income_only，跳过')
      return { skipped: true, reason: 'serviceCharge disabled' }
    }

    // 保留 autoPurchaseEnabled 供下游兼容使用
    var autoPurchaseEnabled = autoSyncMode === 'purchase_and_income' || autoSyncMode === 'purchase_only'

    const enabledDate = settings.serviceChargeEnabledDate
    const chargeNoon = Number(settings.serviceChargeNoon) || 0
    const chargeNight = Number(settings.serviceChargeNight) || 0

    // 2. Extract approval rules from already-loaded settings
    const rules = settings.approval_rules || {}
    const needBanquetApproval = !!(rules && rules.enabled !== false && (rules.categories || {}).banquet === true)
    const amountThreshold = rules && rules.amountThreshold ? Number(rules.amountThreshold) : Infinity

    // 3. Calculate date range: today-3 to today (only past and today, NOT future dates)
    const now = new Date()
    const today = formatDateStr(now)

    const past = new Date(now)
    past.setDate(past.getDate() - 3)
    const threeDaysAgo = formatDateStr(past)

    // 用北京时间日期构造 UTC 查询范围，确保与前端存入的 Date 对齐
    const startDate = beijingStart(threeDaysAgo)
    const endDate = beijingEnd(today)

    let purchaseCreated = 0, incomeCreated = 0, updated = 0, skipped = 0, cleaned = 0

    // =========================================================
    // Phase A: Clean up purchase/income for cancelled reservations
    // =========================================================
    const MAX_LIMIT = 100

    const cancelledReservations = []
    let offset = 0
    while (true) {
      const batchRes = await db.collection('reservation')
        .where({
          date: _.gte(startDate).and(_.lte(endDate)),
          status: 'cancelled'
        })
        .skip(offset)
        .limit(MAX_LIMIT)
        .get()
      const batch = batchRes.data || []
      cancelledReservations.push(...batch)
      if (batch.length < MAX_LIMIT) break
      offset += MAX_LIMIT
    }

    for (const r of cancelledReservations) {
      // Delete auto-generated purchases linked to this cancelled reservation
      const purchaseRes = await db.collection('purchase')
        .where({ sourceReservationId: r._id, category: 'banquet', autoGenerated: true })
        .get()
      for (const p of (purchaseRes.data || [])) {
        await db.collection('purchase').doc(p._id).remove()
        cleaned++
      }

      // Delete auto-generated incomes linked to this cancelled reservation
      const incomeRes = await db.collection('income')
        .where({ reservationId: r._id, autoGenerated: true })
        .get()
      for (const inc of (incomeRes.data || [])) {
        await db.collection('income').doc(inc._id).remove()
        cleaned++
      }
    }

    // =========================================================
    // Phase B: Create/update purchase & income for confirmed reservations
    // 4 modes: income_only / purchase_and_income / purchase_only / none
    // =========================================================
    const shouldCreatePurchase = autoSyncMode === 'purchase_and_income' || autoSyncMode === 'purchase_only'
    const shouldCreateIncome = autoSyncMode === 'income_only' || autoSyncMode === 'purchase_and_income'
    // 单价模式 income_only：服务费模式关闭时，按 standard × guestCount 算收入
    const isUnitPriceIncomeOnly = autoSyncMode === 'income_only' && !serviceChargeEnabled
    // income_only + 服务费模式：收入仅计服务费，无需 dishPrice > 0
    const isServiceChargeIncomeOnly = autoSyncMode === 'income_only' && serviceChargeEnabled

    const reservations = []
    offset = 0
    while (true) {
      const where = {
        date: _.gte(startDate).and(_.lte(endDate)),
        status: 'confirmed',
        hasIncome: _.neq(true)
      }
      if (isUnitPriceIncomeOnly) {
        where.standard = _.gt(0)
      } else if (isServiceChargeIncomeOnly) {
        // income_only + 服务费模式：只要有服务费即可，不需要菜价
        // 不加 dishPrice 限制
      } else {
        where.dishPrice = _.gt(0)
      }
      const batchRes = await db.collection('reservation')
        .where(where)
        .skip(offset)
        .limit(MAX_LIMIT)
        .get()
      const batch = batchRes.data || []
      reservations.push(...batch)
      if (batch.length < MAX_LIMIT) break
      offset += MAX_LIMIT
    }

    console.log('[autoSync] mode=' + autoSyncMode + ', 取消预约=' + cancelledReservations.length + ', 待处理预约=' + reservations.length)

    for (const r of reservations) {
      try {
        const resDate = typeof r.date === 'object' ? formatDateStr(r.date) : r.date

        // 服务费模式需检查 enabledDate；单价模式无此限制
        if (serviceChargeEnabled && enabledDate && resDate < enabledDate) {
          skipped++
          continue
        }

        const isChessRoom = r.room === 'chess' && (r.exclusiveType || 'none') === 'none'
        // 棋牌室不自动创建采购和收入
        if (isChessRoom) continue

        const time = r.time || '中午'
        const charge = time === '中午' ? chargeNoon : chargeNight
        const dishPrice = Number(r.dishPrice) || 0
        const standard = Number(r.standard) || 0
        const guestCount = Number(r.guestCount) || 0

        // 收入金额计算：
        // income_only（仅收入）: 收入 = 仅服务费(charge)，无采购
        // purchase_and_income（采购+收入）: 收入 = 菜价(dishPrice) + 服务费(charge)，采购 = 菜价
        // purchase_only（仅采购）: 无收入，采购 = 菜价
        // 非服务费模式: 收入 = standard × guestCount × 折扣
        let incomeAmount = 0
        let incomeCalcMode = 'dishPrice'
        let incomeDishPrice = 0
        let incomeServiceCharge = 0
        if (serviceChargeEnabled) {
          if (autoSyncMode === 'income_only') {
            // 仅收入模式：收入只计服务费；服务费为0则跳过
            if (charge <= 0) { skipped++; continue }
            incomeAmount = charge
            incomeCalcMode = 'dishPrice'
            incomeDishPrice = 0
            incomeServiceCharge = charge
          } else if (autoSyncMode === 'purchase_and_income') {
            // 采购+收入模式：收入 = 菜价 + 服务费
            incomeAmount = dishPrice + charge
            incomeCalcMode = 'dishPrice'
            incomeDishPrice = dishPrice
            incomeServiceCharge = charge
          } else {
            // purchase_only 或其他：不创建收入，仅备用字段
            incomeAmount = 0
            incomeCalcMode = 'dishPrice'
            incomeDishPrice = 0
            incomeServiceCharge = charge
          }
        } else {
          let unitPrice = standard
          if (r.isPartner) unitPrice = unitPrice * 0.8
          incomeAmount = Math.round(unitPrice * guestCount)
          incomeCalcMode = 'standard'
          incomeDishPrice = 0
          incomeServiceCharge = 0
        }

        // Query purchase & income in parallel (only when needed)
        const incomePromise = shouldCreateIncome
          ? db.collection('income').where({ reservationId: r._id, autoGenerated: true }).get()
          : Promise.resolve({ data: [] })
        const purchasePromise = shouldCreatePurchase
          ? db.collection('purchase').where({ sourceReservationId: r._id, category: 'banquet', autoGenerated: true }).get()
          : Promise.resolve({ data: [] })
        const [purchaseRes, incomeRes] = await Promise.all([purchasePromise, incomePromise])

        // Track purchase ID for income linking
        let linkedPurchaseId = null

        // === Purchase creation/update ===
        if (shouldCreatePurchase && (!purchaseRes.data || purchaseRes.data.length === 0)) {
          const needApproval = needBanquetApproval || (dishPrice > amountThreshold)

          const customerName = r.customerName || ''
          const roomName = r.roomName || ''
          const remark = customerName + ' - ' + roomName

          const purchaseData = {
            amount: dishPrice,
            category: 'banquet',
            date: resDate,
            remark: remark,
            item: '',
            sourceReservationId: r._id,
            venueId: r.venueId || '',
            autoGenerated: true,
            purchaseBy: r.createdBy || '',
            purchaseByName: r.createdByName || '系统自动',
            status: needApproval ? 'pending' : 'approved',
            createdAt: db.serverDate(),
            createdTime: db.serverDate()
          }

          if (needApproval) {
            purchaseData.approverId = rules.defaultApproverId || ''
            purchaseData.approverName = rules.defaultApproverName || ''
          } else {
            purchaseData.approverName = '宴会创建自动批复'
            purchaseData.approvedAt = db.serverDate()
          }

          const purchaseAddResult = await db.collection('purchase').add({ data: purchaseData })
          linkedPurchaseId = purchaseAddResult._id
          purchaseCreated++

          // purchase_only 模式下也标记 hasIncome，防止重复遍历
          if (!shouldCreateIncome) {
            await db.collection('reservation').doc(r._id).update({
              data: { hasIncome: true }
            })
          }
        } else if (shouldCreatePurchase && purchaseRes.data.length > 0) {
          const existingPurchase = purchaseRes.data[0]
          linkedPurchaseId = existingPurchase._id
          const customerName = r.customerName || ''
          const roomName = r.roomName || ''
          const remark = customerName + ' - ' + roomName

          if (existingPurchase.amount !== dishPrice || existingPurchase.remark !== remark || existingPurchase.date !== resDate || existingPurchase.venueId !== (r.venueId || '')) {
            await db.collection('purchase').doc(existingPurchase._id).update({
              data: {
                amount: dishPrice,
                date: resDate,
                remark: remark,
                venueId: r.venueId || existingPurchase.venueId || ''
              }
            })
            updated++
          }
        }

        // === Income creation/update ===
        if (shouldCreateIncome) {
          if (!incomeRes.data || incomeRes.data.length === 0) {
            await db.collection('income').add({
              data: {
                type: 'dining',
                amount: incomeAmount,
                date: resDate,
                source: r.customerName || '',
                reservationId: r._id,
                purchaseId: linkedPurchaseId || '',
                remark: '',
                calcMode: incomeCalcMode,
                dishPrice: incomeDishPrice,
                serviceCharge: incomeServiceCharge,
                guestCount: guestCount,
                standard: standard,
                roomName: r.roomName || '',
                venueId: r.venueId || '',
                autoGenerated: true,
                createdAt: db.serverDate(),
                createdTime: db.serverDate()
              }
            })

            // Mark hasIncome on reservation
            await db.collection('reservation').doc(r._id).update({
              data: { hasIncome: true }
            })
            incomeCreated++
          } else if (incomeRes.data.length > 0) {
            const existingIncome = incomeRes.data[0]
            if (existingIncome.amount !== incomeAmount || existingIncome.dishPrice !== incomeDishPrice || existingIncome.date !== resDate || existingIncome.calcMode !== incomeCalcMode || existingIncome.venueId !== (r.venueId || '')) {
              await db.collection('income').doc(existingIncome._id).update({
                data: {
                  amount: incomeAmount,
                  date: resDate,
                  source: r.customerName || '',
                  purchaseId: linkedPurchaseId || existingIncome.purchaseId || '',
                  calcMode: incomeCalcMode,
                  dishPrice: incomeDishPrice,
                  serviceCharge: incomeServiceCharge,
                  guestCount: guestCount,
                  standard: standard,
                  roomName: r.roomName || '',
                  venueId: r.venueId || existingIncome.venueId || ''
                }
              })
              updated++
            }
          }
        }
      } catch (err) {
        console.error('[autoSync] 处理预约失败, id=' + r._id, err)
      }
    }

    console.log('[autoSync] 完成: purchaseCreated=' + purchaseCreated + ', incomeCreated=' + incomeCreated + ', updated=' + updated + ', skipped=' + skipped + ', cleaned=' + cleaned)
    return { purchaseCreated, incomeCreated, updated, skipped, cleaned }
  } catch (err) {
    console.error('[autoSync] 错误:', err)
    return { error: err.message }
  }
}
