const cloud = require('wx-server-sdk')
cloud.init({ env: cloud.DYNAMIC_CURRENT_ENV })
const db = cloud.database()
const _ = db.command

function formatDateStr(d) {
  return d.getFullYear() + '-' + String(d.getMonth() + 1).padStart(2, '0') + '-' + String(d.getDate()).padStart(2, '0')
}

/**
 * Daily timer — auto create banquet purchase & income for reservations on today's date.
 * Also backfills past 3 days as a safety net.
 * Cleans up purchase/income for cancelled reservations.
 * Skips reservations that already have linked records.
 */
exports.main = async (event, context) => {
  try {
    // 1. Load needed settings precisely (including approval_rules in single query)
    const neededKeys = ['serviceChargeEnabled', 'serviceChargeEnabledDate', 'serviceChargeNoon', 'serviceChargeNight', 'approval_rules']
    const settingsRes = await db.collection('settings').where({ key: _.in(neededKeys) }).get()
    const settings = {}
    ;(settingsRes.data || []).forEach(s => { if (!(s.key in settings)) settings[s.key] = s.value })

    if (!settings.serviceChargeEnabled) {
      console.log('[autoSync] 服务费模式未开启，跳过')
      return { skipped: true, reason: 'serviceCharge disabled' }
    }

    const enabledDate = settings.serviceChargeEnabledDate
    const chargeNoon = Number(settings.serviceChargeNoon) || 0
    const chargeNight = Number(settings.serviceChargeNight) || 0

    // 2. Extract approval rules from already-loaded settings
    const rules = settings.approval_rules || {}
    const needBanquetApproval = !!(rules && rules.enabled !== false && (rules.categories || {}).banquet === true)
    const amountThreshold = rules && rules.amountThreshold ? Number(rules.amountThreshold) : Infinity

    // 3. Calculate date range: today-3 to today
    const now = new Date()
    const today = formatDateStr(now)

    const past = new Date(now)
    past.setDate(past.getDate() - 3)
    const threeDaysAgo = formatDateStr(past)

    const startDate = new Date(threeDaysAgo + 'T00:00:00')
    const endDate = new Date(today + 'T23:59:59')

    let purchaseCreated = 0, incomeCreated = 0, updated = 0, skipped = 0, cleaned = 0

    // =========================================================
    // Phase A: Clean up purchase/income for cancelled reservations
    // =========================================================
    const MAX_LIMIT = 100

    const cancelledReservations = []
    let offset = 0
    while (true) {
      const batchRes = await db.collection('reservation')
        .where({
          date: _.gte(startDate).and(_.lte(endDate)),
          status: 'cancelled'
        })
        .skip(offset)
        .limit(MAX_LIMIT)
        .get()
      const batch = batchRes.data || []
      cancelledReservations.push(...batch)
      if (batch.length < MAX_LIMIT) break
      offset += MAX_LIMIT
    }

    for (const r of cancelledReservations) {
      // Delete auto-generated purchases linked to this cancelled reservation
      const purchaseRes = await db.collection('purchase')
        .where({ sourceReservationId: r._id, category: 'banquet', autoGenerated: true })
        .get()
      for (const p of (purchaseRes.data || [])) {
        await db.collection('purchase').doc(p._id).remove()
        cleaned++
      }

      // Delete auto-generated incomes linked to this cancelled reservation
      const incomeRes = await db.collection('income')
        .where({ reservationId: r._id, autoGenerated: true })
        .get()
      for (const inc of (incomeRes.data || [])) {
        await db.collection('income').doc(inc._id).remove()
        cleaned++
      }
    }

    // =========================================================
    // Phase B: Create/update purchase & income for confirmed reservations
    // =========================================================
    const reservations = []
    offset = 0
    while (true) {
      const batchRes = await db.collection('reservation')
        .where({
          date: _.gte(startDate).and(_.lte(endDate)),
          status: 'confirmed',
          dishPrice: _.gt(0)
        })
        .skip(offset)
        .limit(MAX_LIMIT)
        .get()
      const batch = batchRes.data || []
      reservations.push(...batch)
      if (batch.length < MAX_LIMIT) break
      offset += MAX_LIMIT
    }

    console.log('[autoSync] 取消预约=' + cancelledReservations.length + ', 待处理预约=' + reservations.length)

    for (const r of reservations) {
      const resDate = typeof r.date === 'object' ? formatDateStr(r.date) : r.date

      // Check serviceChargeEnabledDate
      if (resDate < enabledDate) {
        skipped++
        continue
      }

      const time = r.time || '中午'
      const charge = time === '中午' ? chargeNoon : chargeNight
      const dishPrice = Number(r.dishPrice) || 0

      // Query purchase & income in parallel (only auto-generated records)
      const [purchaseRes, incomeRes] = await Promise.all([
        db.collection('purchase').where({ sourceReservationId: r._id, category: 'banquet', autoGenerated: true }).get(),
        db.collection('income').where({ reservationId: r._id, autoGenerated: true }).get()
      ])

      // Generate or update purchase
      if (!purchaseRes.data || purchaseRes.data.length === 0) {
        const needApproval = needBanquetApproval || (dishPrice > amountThreshold)

        const customerName = r.customerName || ''
        const roomName = r.roomName || ''
        const remark = customerName + ' - ' + roomName

        const purchaseData = {
          amount: dishPrice,
          category: 'banquet',
          date: resDate,
          remark: remark,
          item: '',
          sourceReservationId: r._id,
          autoGenerated: true,
          status: needApproval ? 'pending' : 'approved',
          createdTime: db.serverDate()
        }

        if (needApproval) {
          purchaseData.approverId = rules.defaultApproverId || ''
          purchaseData.approverName = rules.defaultApproverName || ''
        }

        await db.collection('purchase').add({ data: purchaseData })
        purchaseCreated++
      } else if (purchaseRes.data.length > 0) {
        const existingPurchase = purchaseRes.data[0]
        const customerName = r.customerName || ''
        const roomName = r.roomName || ''
        const remark = customerName + ' - ' + roomName

        if (existingPurchase.amount !== dishPrice || existingPurchase.remark !== remark || existingPurchase.date !== resDate) {
          await db.collection('purchase').doc(existingPurchase._id).update({
            data: {
              amount: dishPrice,
              date: resDate,
              remark: remark
            }
          })
          updated++
        }
      }

      // Generate or update income
      const amount = dishPrice + charge

      if (!incomeRes.data || incomeRes.data.length === 0) {
        await db.collection('income').add({
          data: {
            type: 'dining',
            amount: amount,
            date: resDate,
            source: r.customerName || '',
            reservationId: r._id,
            remark: '',
            calcMode: 'dishPrice',
            dishPrice: dishPrice,
            serviceCharge: charge,
            guestCount: r.guestCount || 0,
            standard: r.standard || 0,
            roomName: r.roomName || '',
            autoGenerated: true,
            createdTime: db.serverDate()
          }
        })

        // Mark hasIncome on reservation
        await db.collection('reservation').doc(r._id).update({
          data: { hasIncome: true }
        })
        incomeCreated++
      } else if (incomeRes.data.length > 0) {
        const existingIncome = incomeRes.data[0]
        if (existingIncome.amount !== amount || existingIncome.dishPrice !== dishPrice || existingIncome.date !== resDate) {
          await db.collection('income').doc(existingIncome._id).update({
            data: {
              amount: amount,
              date: resDate,
              source: r.customerName || '',
              dishPrice: dishPrice,
              serviceCharge: charge,
              guestCount: r.guestCount || 0,
              standard: r.standard || 0,
              roomName: r.roomName || ''
            }
          })
          updated++
        }
      }
    }

    console.log('[autoSync] 完成: purchaseCreated=' + purchaseCreated + ', incomeCreated=' + incomeCreated + ', updated=' + updated + ', skipped=' + skipped + ', cleaned=' + cleaned)
    return { purchaseCreated, incomeCreated, updated, skipped, cleaned }
  } catch (err) {
    console.error('[autoSync] 错误:', err)
    return { error: err.message }
  }
}
