/**
 * sync.js - Banquet purchase / income synchronization for reservation-add.
 *
 * Pure functions (no `this` reference) that take a docData + reservationId
 * and reconcile the matching purchase / income records. The page module
 * calls these after creating or updating a reservation.
 *
 * All functions swallow internal errors with console.warn — sync failures
 * should never block the primary reservation save.
 */
const db = require('../../../utils/db')
const { COLLECTIONS } = require('../../../utils/db')
const { formatDate } = require('../../../utils/helpers')

/**
 * Determine whether the room has no meal standards configured.
 * Such rooms (e.g. 棋牌室) skip purchase/income auto-sync.
 */
function isNoStandardRoom(roomConfig, exclusiveType) {
  if (!roomConfig) return false
  const standards = roomConfig.standards || []
  return standards.length === 0 && exclusiveType === 'none'
}

/**
 * Sync banquet purchase for the reservation.
 * - dishPrice > 0 → upsert a purchase record (auto-approved or pending based on rules)
 * - dishPrice === 0 → delete any auto-generated purchase record
 */
async function syncBanquetPurchase({ docData, reservationId, isCreate, roomConfig, settings, userInfo }) {
  try {
    if (isNoStandardRoom(roomConfig, docData.exclusiveType)) return

    const dishPrice = Number(docData.dishPrice) || 0
    const existing = await db.queryAll(COLLECTIONS.PURCHASE, { sourceReservationId: reservationId })
    const hasExisting = existing.data && existing.data.length > 0
    const first = hasExisting ? existing.data[0] : null

    if (dishPrice > 0) {
      const remark = (docData.customerName || '') + ' - ' + (docData.roomName || '')
      const now = new Date()

      const rules = (settings && settings.approval_rules) || {}
      const needBanquetApproval = !!(rules.enabled !== false && (rules.categories || {}).banquet === true)
      const amountThreshold = rules.amountThreshold ? Number(rules.amountThreshold) : Infinity
      const needApproval = needBanquetApproval || (dishPrice > amountThreshold)

      const purchaseData = {
        amount: dishPrice, category: 'banquet',
        date: formatDate(docData.date), remark: remark, item: '',
        purchaseBy: userInfo._id || '',
        purchaseByName: userInfo.name || userInfo.nickName || '',
        sourceReservationId: reservationId, autoGenerated: true,
        status: needApproval ? 'pending' : 'approved',
        approverName: needApproval ? (rules.defaultApproverName || '') : '宴会创建自动批复',
        ...(needApproval
          ? { approverId: rules.defaultApproverId || '' }
          : { approvedAt: now })
      }
      if (!purchaseData.purchaseBy) delete purchaseData.purchaseBy

      if (hasExisting) {
        if (!isCreate) await db.updateDoc(COLLECTIONS.PURCHASE, first._id, purchaseData)
      } else {
        const addResult = await db.addDoc(COLLECTIONS.PURCHASE, purchaseData)
        if (!needApproval) {
          await db.addDoc(COLLECTIONS.APPROVAL_LOG, {
            purchaseId: addResult._id, action: 'approved',
            operatorId: '', operatorName: '宴会创建自动批复',
            remark: '宴会预约创建时自动批复', createdAt: now
          }).catch(function(e) { console.warn('[banquet-sync] 自动审批日志写入失败:', e) })
        }
      }
    } else {
      if (first && first.autoGenerated) {
        await db.deleteDoc(COLLECTIONS.PURCHASE, first._id)
      }
    }
  } catch (err) {
    console.warn('[banquet-sync] 同步宴会菜价失败:', err)
  }
}

/**
 * Sync income for the reservation.
 * Only triggered when service charge mode is enabled and dishPrice > 0.
 */
async function syncIncome({ docData, reservationId, isCreate, roomConfig, settings, userInfo }) {
  try {
    if (isNoStandardRoom(roomConfig, docData.exclusiveType)) return

    const dishPrice = Number(docData.dishPrice) || 0
    if (dishPrice <= 0) return

    const time = docData.time || '中午'
    const chargeNoon = Number(settings.serviceChargeNoon) || 0
    const chargeNight = Number(settings.serviceChargeNight) || 0
    const charge = time === '中午' ? chargeNoon : chargeNight
    const amount = dishPrice + charge

    const existing = await db.queryAll(COLLECTIONS.INCOME, { reservationId: reservationId })
    const hasExisting = existing.data && existing.data.length > 0
    const first = hasExisting ? existing.data[0] : null

    const incomeData = {
      type: 'dining', amount: amount,
      date: formatDate(docData.date),
      source: docData.customerName || '',
      reservationId: reservationId,
      remark: '',
      collectedBy: userInfo._id || '',
      collectedByName: userInfo.name || '',
      calcMode: 'dishPrice',
      dishPrice: dishPrice,
      serviceCharge: charge,
      guestCount: docData.guestCount || 0,
      standard: docData.standard || 0,
      roomName: docData.roomName || '',
      autoGenerated: true
    }

    if (hasExisting) {
      if (!isCreate) await db.updateDoc(COLLECTIONS.INCOME, first._id, incomeData)
    } else {
      await db.addDoc(COLLECTIONS.INCOME, incomeData)
      await db.updateDoc(COLLECTIONS.RESERVATION, reservationId, { hasIncome: true })
    }
  } catch (err) {
    console.warn('[banquet-sync] 同步收入失败:', err)
  }
}

/**
 * Delete all auto-generated purchase / income records linked to a reservation.
 * Called when the reservation itself is deleted.
 */
async function deleteBanquetPurchase(reservationId) {
  try {
    const purchases = await db.queryAll(COLLECTIONS.PURCHASE, {
      sourceReservationId: reservationId, autoGenerated: true
    })
    for (let i = 0; i < (purchases.data || []).length; i++) {
      await db.deleteDoc(COLLECTIONS.PURCHASE, purchases.data[i]._id)
    }
    const incomes = await db.queryAll(COLLECTIONS.INCOME, {
      reservationId: reservationId, autoGenerated: true
    })
    for (let j = 0; j < (incomes.data || []).length; j++) {
      await db.deleteDoc(COLLECTIONS.INCOME, incomes.data[j]._id)
    }
  } catch (err) {
    console.warn('[banquet-sync] 删除关联记录失败:', err)
  }
}

module.exports = {
  syncBanquetPurchase,
  syncIncome,
  deleteBanquetPurchase,
  isNoStandardRoom
}
