/**
 * sync.js - Banquet purchase / income synchronization for reservation-add.
 *
 * Pure functions (no `this` reference) that take a docData + reservationId
 * and reconcile the matching purchase / income records. The page module
 * calls these after creating or updating a reservation.
 *
 * All functions swallow internal errors with console.warn — sync failures
 * should never block the primary reservation save.
 */
const db = require('../../../utils/db')
const { COLLECTIONS } = require('../../../utils/db')
const { formatDate } = require('../../../utils/helpers')

/**
 * Determine whether the room has no meal standards configured.
 * Such rooms (e.g. 棋牌室) skip purchase/income auto-sync.
 */
function isNoStandardRoom(roomConfig, exclusiveType) {
  if (!roomConfig) return false
  const standards = roomConfig.standards || []
  return standards.length === 0 && exclusiveType === 'none'
}

/**
 * Sync banquet purchase AND income for the reservation.
 * - dishPrice > 0 → upsert a purchase record, then generate income from purchase + service charge
 * - dishPrice === 0 → delete any auto-generated purchase and income records
 *
 * Income is now derived from the submitted banquet purchase (宴会菜价) + service charge,
 * NOT directly from the reservation's dishPrice field.
 */
async function syncBanquetPurchase({ docData, reservationId, isCreate, roomConfig, settings, userInfo }) {
  try {
    if (isNoStandardRoom(roomConfig, docData.exclusiveType)) return

    const dishPrice = Number(docData.dishPrice) || 0
    const existing = await db.queryAll(COLLECTIONS.PURCHASE, { sourceReservationId: reservationId })
    const hasExisting = existing.data && existing.data.length > 0
    const first = hasExisting ? existing.data[0] : null

    if (dishPrice > 0) {
      const remark = (docData.customerName || '') + ' - ' + (docData.roomName || '')
      const now = new Date()

      const rules = (settings && settings.approval_rules) || {}
      const needBanquetApproval = !!(rules.enabled !== false && (rules.categories || {}).banquet === true)
      const amountThreshold = rules.amountThreshold ? Number(rules.amountThreshold) : Infinity
      const needApproval = needBanquetApproval || (dishPrice > amountThreshold)

      const purchaseData = {
        amount: dishPrice, category: 'banquet',
        date: formatDate(docData.date), remark: remark, item: '',
        purchaseBy: userInfo._id || '',
        purchaseByName: userInfo.name || userInfo.nickName || '',
        sourceReservationId: reservationId, autoGenerated: true,
        status: needApproval ? 'pending' : 'approved',
        approverName: needApproval ? (rules.defaultApproverName || '') : '宴会创建自动批复',
        ...(needApproval
          ? { approverId: rules.defaultApproverId || '' }
          : { approvedAt: now })
      }
      if (!purchaseData.purchaseBy) delete purchaseData.purchaseBy

      let purchaseId = null
      if (hasExisting) {
        if (!isCreate) await db.updateDoc(COLLECTIONS.PURCHASE, first._id, purchaseData)
        purchaseId = first._id
      } else {
        const addResult = await db.addDoc(COLLECTIONS.PURCHASE, purchaseData)
        purchaseId = addResult._id
        if (!needApproval) {
          await db.addDoc(COLLECTIONS.APPROVAL_LOG, {
            purchaseId: addResult._id, action: 'approved',
            operatorId: '', operatorName: '宴会创建自动批复',
            remark: '宴会预约创建时自动批复', createdAt: now
          }).catch(function(e) { console.warn('[banquet-sync] 自动审批日志写入失败:', e) })
        }
      }

      // Generate income from the submitted banquet purchase + service charge
      await syncIncomeFromPurchase({
        purchaseId: purchaseId,
        purchaseAmount: dishPrice,
        reservationData: docData,
        reservationId: reservationId,
        settings: settings,
        userInfo: userInfo
      })
    } else {
      if (first && first.autoGenerated) {
        await deleteIncomeByPurchase(first._id, reservationId)
        await db.deleteDoc(COLLECTIONS.PURCHASE, first._id)
      }
    }
  } catch (err) {
    console.warn('[banquet-sync] 同步宴会菜价失败:', err)
  }
}

/**
 * Generate or update income based on a banquet purchase (submitted dish price) + service charge.
 * Income amount = purchaseAmount + serviceCharge (from settings based on reservation time slot).
 *
 * For NEW income, tries stored-value deduction first via settleIncomeWithStoredValue cloud function.
 * Falls back to direct income creation if no stored-value account exists or on error.
 *
 * For UPDATE, skips if the existing income is stored-value linked (cannot modify settled amounts).
 */
async function syncIncomeFromPurchase({ purchaseId, purchaseAmount, reservationData, reservationId, settings, userInfo }) {
  try {
    const time = (reservationData && reservationData.time) || '中午'
    const chargeNoon = Number(settings.serviceChargeNoon) || 0
    const chargeNight = Number(settings.serviceChargeNight) || 0
    const charge = time === '中午' ? chargeNoon : chargeNight
    const amount = purchaseAmount + charge

    // Find existing auto-generated income linked to this reservation (covers both
    // new purchaseId-linked records and legacy reservationId-only records)
    const existing = await db.queryAll(COLLECTIONS.INCOME, { reservationId: reservationId, autoGenerated: true })
    const hasExisting = existing.data && existing.data.length > 0
    const first = hasExisting ? existing.data[0] : null

    if (hasExisting) {
      // === UPDATE PATH ===
      // If the income was already settled via stored-value, skip (cannot modify)
      if (first && first.settlementMode && String(first.settlementMode).indexOf('stored_') === 0) {
        console.log('[banquet-sync] UPDATE path: skipped (stored-value linked income)')
        return
      }
      console.log('[banquet-sync] UPDATE path: updating income ' + first._id + ' from ' + (first.amount) + ' to ' + amount)
      // Otherwise update amount directly (e.g. dishPrice changed on reservation)
      const incomeData = {
        type: 'dining', amount: amount,
        date: formatDate(reservationData.date),
        source: (reservationData && reservationData.customerName) || '',
        reservationId: reservationId,
        purchaseId: purchaseId,
        remark: '',
        collectedBy: (userInfo && userInfo._id) || '',
        collectedByName: (userInfo && userInfo.name) || '',
        calcMode: 'dishPrice',
        dishPrice: purchaseAmount,
        serviceCharge: charge,
        guestCount: (reservationData && reservationData.guestCount) || 0,
        standard: (reservationData && reservationData.standard) || 0,
        roomName: (reservationData && reservationData.roomName) || '',
        autoGenerated: true
      }
      if (!incomeData.collectedBy) delete incomeData.collectedBy
      await db.updateDoc(COLLECTIONS.INCOME, first._id, incomeData)
      console.log('[banquet-sync] UPDATE path: income updated successfully')
      return
    }

    // === CREATE PATH ===
    // Try stored-value settlement via cloud function first
    let settledByCloud = false
    try {
      const _collectedBy = (userInfo && userInfo._id) || ''
      const _collectedByName = (userInfo && userInfo.name) || ''
      const response = await wx.cloud.callFunction({
        name: 'storedValue',
        data: {
          action: 'settleIncomeWithStoredValue',
          amount: amount,
          date: formatDate(reservationData.date),
          type: 'dining',
          reservationId: reservationId,
          reservationSnapshot: reservationData,
          remark: '',
          collectedBy: _collectedBy,
          collectedByName: _collectedByName,
          // Metadata — picked by pickIncomeMetadata in cloud function
          autoGenerated: true,
          purchaseId: purchaseId,
          calcMode: 'dishPrice',
          dishPrice: purchaseAmount,
          serviceCharge: charge,
          guestCount: (reservationData && reservationData.guestCount) || 0,
          standard: (reservationData && reservationData.standard) || 0,
          roomName: (reservationData && reservationData.roomName) || ''
        }
      })
      const result = response && response.result
      if (result && result.success !== false) {
        // Cloud function succeeded. Only skip fallback if it actually created an income.
        // (Old cloud function for stored_full returns success but doesn't create income)
        const incomeId = result.data && result.data.incomeId
        if (incomeId) {
          settledByCloud = true
        } else {
          console.log('[banquet-sync] 云函数结算成功但未创建收入记录(settlementMode=' + (result.data && result.data.settlementMode) + ')，走回退路径创建')
        }
      }
    } catch (e) {
      console.warn('[banquet-sync] 储值结算失败，回退到直接创建收入:', e && e.errCode, e && e.errMsg)
    }

    if (!settledByCloud) {
      console.log('[banquet-sync] 回退路径：直接创建收入, reservationId=' + reservationId + ', amount=' + amount)
      const incomeData = {
        type: 'dining', amount: amount,
        date: formatDate(reservationData.date),
        source: (reservationData && reservationData.customerName) || '',
        reservationId: reservationId,
        purchaseId: purchaseId,
        remark: '',
        collectedBy: (userInfo && userInfo._id) || '',
        collectedByName: (userInfo && userInfo.name) || '',
        calcMode: 'dishPrice',
        dishPrice: purchaseAmount,
        serviceCharge: charge,
        guestCount: (reservationData && reservationData.guestCount) || 0,
        standard: (reservationData && reservationData.standard) || 0,
        roomName: (reservationData && reservationData.roomName) || '',
        autoGenerated: true
      }
      if (!incomeData.collectedBy) delete incomeData.collectedBy
      await db.addDoc(COLLECTIONS.INCOME, incomeData)
      await db.updateDoc(COLLECTIONS.RESERVATION, reservationId, { hasIncome: true })
    }
  } catch (err) {
    console.warn('[banquet-sync] 从采购生成收入失败:', err)
  }
}

/**
 * Delete auto-generated income linked to a purchase.
 * Queries by purchaseId first, then falls back to reservationId for legacy records.
 */
async function deleteIncomeByPurchase(purchaseId, reservationId) {
  try {
    // Delete income linked by purchaseId
    var incomes = await db.queryAll(COLLECTIONS.INCOME, { purchaseId: purchaseId, autoGenerated: true })
    for (var i = 0; i < (incomes.data || []).length; i++) {
      await db.deleteDoc(COLLECTIONS.INCOME, incomes.data[i]._id)
    }
    // Fallback: delete legacy income linked only by reservationId (no purchaseId)
    if (reservationId) {
      var legacy = await db.queryAll(COLLECTIONS.INCOME, { reservationId: reservationId, autoGenerated: true })
      for (var j = 0; j < (legacy.data || []).length; j++) {
        await db.deleteDoc(COLLECTIONS.INCOME, legacy.data[j]._id)
      }
    }
    // Reset hasIncome on the reservation — allows re-generation of income
    if (reservationId) {
      await db.updateDoc(COLLECTIONS.RESERVATION, reservationId, { hasIncome: false })
    }
  } catch (err) {
    console.warn('[banquet-sync] 删除关联收入失败:', err)
  }
}

/**
 * Delete all auto-generated purchase / income records linked to a reservation.
 * Called when the reservation itself is deleted.
 */
async function deleteBanquetPurchase(reservationId) {
  try {
    const purchases = await db.queryAll(COLLECTIONS.PURCHASE, {
      sourceReservationId: reservationId, autoGenerated: true
    })
    for (let i = 0; i < (purchases.data || []).length; i++) {
      var p = purchases.data[i]
      // Delete income linked to this purchase before deleting the purchase
      await deleteIncomeByPurchase(p._id, reservationId)
      await db.deleteDoc(COLLECTIONS.PURCHASE, p._id)
    }
  } catch (err) {
    console.warn('[banquet-sync] 删除关联记录失败:', err)
  }
}

/**
 * Calculate income amount based on reservation data and settings.
 * - Service fee mode: dishPrice + serviceCharge
 * - Unit price mode: standard × guestCount × (0.8 if isPartner)
 * Returns { amount, calcMode, dishPrice, serviceCharge }.
 */
function calculateIncome(docData, settings) {
  const serviceChargeEnabled = !!(settings && settings.serviceChargeEnabled)
  const time = (docData && docData.time) || '中午'
  const chargeNoon = Number(settings && settings.serviceChargeNoon) || 0
  const chargeNight = Number(settings && settings.serviceChargeNight) || 0
  const charge = time === '中午' ? chargeNoon : chargeNight
  const dishPrice = Number(docData && docData.dishPrice) || 0
  const standard = Number(docData && docData.standard) || 0
  const guestCount = Number(docData && docData.guestCount) || 0

  if (serviceChargeEnabled) {
    return {
      amount: dishPrice + charge,
      calcMode: 'dishPrice',
      dishPrice: dishPrice,
      serviceCharge: charge
    }
  }
  let unitPrice = standard
  if (docData && docData.isPartner) unitPrice = unitPrice * 0.8
  return {
    amount: Math.round(unitPrice * guestCount),
    calcMode: 'standard',
    dishPrice: 0,
    serviceCharge: 0
  }
}

/**
 * Income-only mode: create/update income without creating purchase.
 * Used when autoSyncMode === 'income_only'.
 */
async function syncIncomeFromReservation({ docData, reservationId, settings, userInfo }) {
  try {
    const calc = calculateIncome(docData, settings)
    if (calc.amount <= 0) return

    const existing = await db.queryAll(COLLECTIONS.INCOME, { reservationId: reservationId, autoGenerated: true })
    const hasExisting = existing.data && existing.data.length > 0
    const first = hasExisting ? existing.data[0] : null

    const incomeData = {
      type: 'dining', amount: calc.amount,
      date: formatDate(docData.date),
      source: (docData && docData.customerName) || '',
      reservationId: reservationId,
      purchaseId: '',
      remark: '',
      collectedBy: (userInfo && userInfo._id) || '',
      collectedByName: (userInfo && userInfo.name) || '',
      calcMode: calc.calcMode,
      dishPrice: calc.dishPrice,
      serviceCharge: calc.serviceCharge,
      guestCount: (docData && docData.guestCount) || 0,
      standard: (docData && docData.standard) || 0,
      roomName: (docData && docData.roomName) || '',
      autoGenerated: true
    }
    if (!incomeData.collectedBy) delete incomeData.collectedBy

    if (hasExisting) {
      if (first && first.settlementMode && String(first.settlementMode).indexOf('stored_') === 0) {
        console.log('[income-only] 跳过储值关联收入更新')
        return
      }
      await db.updateDoc(COLLECTIONS.INCOME, first._id, incomeData)
      return
    }

    // Create path: try stored-value settlement first, fallback to direct create
    let settledByCloud = false
    try {
      const _collectedBy = (userInfo && userInfo._id) || ''
      const _collectedByName = (userInfo && userInfo.name) || ''
      const response = await wx.cloud.callFunction({
        name: 'storedValue',
        data: {
          action: 'settleIncomeWithStoredValue',
          amount: calc.amount,
          date: formatDate(docData.date),
          type: 'dining',
          reservationId: reservationId,
          reservationSnapshot: docData,
          remark: '',
          collectedBy: _collectedBy,
          collectedByName: _collectedByName,
          autoGenerated: true,
          purchaseId: '',
          calcMode: calc.calcMode,
          dishPrice: calc.dishPrice,
          serviceCharge: calc.serviceCharge,
          guestCount: (docData && docData.guestCount) || 0,
          standard: (docData && docData.standard) || 0,
          roomName: (docData && docData.roomName) || ''
        }
      })
      const result = response && response.result
      if (result && result.success !== false && result.data && result.data.incomeId) {
        settledByCloud = true
      }
    } catch (e) {
      console.warn('[income-only] 储值结算失败，回退直接创建:', e && e.errMsg)
    }

    if (!settledByCloud) {
      await db.addDoc(COLLECTIONS.INCOME, incomeData)
      await db.updateDoc(COLLECTIONS.RESERVATION, reservationId, { hasIncome: true })
    }
  } catch (err) {
    console.warn('[income-only] 自动生成收入失败:', err)
  }
}

/**
 * Purchase-only mode: create/update purchase without creating income.
 * Used when autoSyncMode === 'purchase_only'.
 */
async function syncPurchaseOnly({ docData, reservationId, isCreate, roomConfig, settings, userInfo }) {
  try {
    if (isNoStandardRoom(roomConfig, docData.exclusiveType)) return

    const dishPrice = Number(docData.dishPrice) || 0
    const existing = await db.queryAll(COLLECTIONS.PURCHASE, { sourceReservationId: reservationId })
    const hasExisting = existing.data && existing.data.length > 0
    const first = hasExisting ? existing.data[0] : null

    if (dishPrice > 0) {
      const remark = (docData.customerName || '') + ' - ' + (docData.roomName || '')
      const now = new Date()

      const rules = (settings && settings.approval_rules) || {}
      const needBanquetApproval = !!(rules.enabled !== false && (rules.categories || {}).banquet === true)
      const amountThreshold = rules.amountThreshold ? Number(rules.amountThreshold) : Infinity
      const needApproval = needBanquetApproval || (dishPrice > amountThreshold)

      const purchaseData = {
        amount: dishPrice, category: 'banquet',
        date: formatDate(docData.date), remark: remark, item: '',
        purchaseBy: userInfo._id || '',
        purchaseByName: userInfo.name || userInfo.nickName || '',
        sourceReservationId: reservationId, autoGenerated: true,
        status: needApproval ? 'pending' : 'approved',
        approverName: needApproval ? (rules.defaultApproverName || '') : '宴会创建自动批复',
        ...(needApproval
          ? { approverId: rules.defaultApproverId || '' }
          : { approvedAt: now })
      }
      if (!purchaseData.purchaseBy) delete purchaseData.purchaseBy

      if (hasExisting) {
        if (!isCreate) await db.updateDoc(COLLECTIONS.PURCHASE, first._id, purchaseData)
      } else {
        const addResult = await db.addDoc(COLLECTIONS.PURCHASE, purchaseData)
        if (!needApproval) {
          await db.addDoc(COLLECTIONS.APPROVAL_LOG, {
            purchaseId: addResult._id, action: 'approved',
            operatorId: '', operatorName: '宴会创建自动批复',
            remark: '宴会预约创建时自动批复', createdAt: now
          }).catch(function(e) { console.warn('[purchase-only] 自动审批日志写入失败:', e) })
        }
      }
    } else {
      if (first && first.autoGenerated) {
        await db.deleteDoc(COLLECTIONS.PURCHASE, first._id)
      }
    }
  } catch (err) {
    console.warn('[purchase-only] 同步采购失败:', err)
  }
}

/**
 * Dispatcher: route to the correct sync function based on autoSyncMode.
 * Modes: 'none' | 'income_only' | 'purchase_and_income' | 'purchase_only'
 */
async function syncReservationRecords({ docData, reservationId, isCreate, roomConfig, settings, userInfo }) {
  try {
    const rules = (settings && settings.approval_rules) || {}
    let mode = rules.autoSyncMode
    if (!mode) {
      mode = rules.autoPurchaseEnabled === false ? 'none' : 'purchase_and_income'
    }
    if (mode === 'none') return
    if (isNoStandardRoom(roomConfig, docData.exclusiveType)) return

    if (mode === 'income_only') {
      await syncIncomeFromReservation({ docData, reservationId, settings, userInfo })
    } else if (mode === 'purchase_only') {
      await syncPurchaseOnly({ docData, reservationId, isCreate, roomConfig, settings, userInfo })
    } else {
      // purchase_and_income (default)
      await syncBanquetPurchase({ docData, reservationId, isCreate, roomConfig, settings, userInfo })
    }
  } catch (err) {
    console.warn('[sync-dispatcher] 分发失败:', err)
  }
}

module.exports = {
  syncBanquetPurchase,
  syncIncomeFromPurchase,
  syncIncomeFromReservation,
  syncPurchaseOnly,
  syncReservationRecords,
  deleteIncomeByPurchase,
  deleteBanquetPurchase,
  isNoStandardRoom
}
