/**
 * sync.js - Banquet purchase / income synchronization for reservation-add.
 *
 * Pure functions (no `this` reference) that take a docData + reservationId
 * and reconcile the matching purchase / income records. The page module
 * calls these after creating or updating a reservation.
 *
 * All functions swallow internal errors with console.warn — sync failures
 * should never block the primary reservation save.
 */
const db = require('../../../utils/db')
const { COLLECTIONS } = require('../../../utils/db')
const { formatDate } = require('../../../utils/helpers')

/**
 * Determine whether the room has no meal standards configured.
 * Such rooms (e.g. 棋牌室) skip purchase/income auto-sync.
 */
function isNoStandardRoom(roomConfig, exclusiveType) {
  if (!roomConfig) return false
  const standards = roomConfig.standards || []
  return standards.length === 0 && exclusiveType === 'none'
}

/**
 * Sync banquet purchase AND income for the reservation.
 * - dishPrice > 0 → upsert a purchase record, then generate income from purchase + service charge
 * - dishPrice === 0 → delete any auto-generated purchase and income records
 *
 * Income is now derived from the submitted banquet purchase (宴会菜价) + service charge,
 * NOT directly from the reservation's dishPrice field.
 */
async function syncBanquetPurchase({ docData, reservationId, isCreate, roomConfig, settings, userInfo }) {
  try {
    if (isNoStandardRoom(roomConfig, docData.exclusiveType)) return

    const dishPrice = Number(docData.dishPrice) || 0
    const existing = await db.queryAll(COLLECTIONS.PURCHASE, { sourceReservationId: reservationId })
    const hasExisting = existing.data && existing.data.length > 0
    const first = hasExisting ? existing.data[0] : null

    if (dishPrice > 0) {
      const remark = (docData.customerName || '') + ' - ' + (docData.roomName || '')
      const now = new Date()

      const rules = (settings && settings.approval_rules) || {}
      const needBanquetApproval = !!(rules.enabled !== false && (rules.categories || {}).banquet === true)
      const amountThreshold = rules.amountThreshold ? Number(rules.amountThreshold) : Infinity
      const needApproval = needBanquetApproval || (dishPrice > amountThreshold)

      const purchaseData = {
        amount: dishPrice, category: 'banquet',
        date: formatDate(docData.date), remark: remark, item: '',
        purchaseBy: userInfo._id || '',
        purchaseByName: userInfo.name || userInfo.nickName || '',
        sourceReservationId: reservationId, autoGenerated: true,
        status: needApproval ? 'pending' : 'approved',
        approverName: needApproval ? (rules.defaultApproverName || '') : '宴会创建自动批复',
        ...(needApproval
          ? { approverId: rules.defaultApproverId || '' }
          : { approvedAt: now })
      }
      if (!purchaseData.purchaseBy) delete purchaseData.purchaseBy

      let purchaseId = null
      if (hasExisting) {
        if (!isCreate) await db.updateDoc(COLLECTIONS.PURCHASE, first._id, purchaseData)
        purchaseId = first._id
      } else {
        const addResult = await db.addDoc(COLLECTIONS.PURCHASE, purchaseData)
        purchaseId = addResult._id
        if (!needApproval) {
          await db.addDoc(COLLECTIONS.APPROVAL_LOG, {
            purchaseId: addResult._id, action: 'approved',
            operatorId: '', operatorName: '宴会创建自动批复',
            remark: '宴会预约创建时自动批复', createdAt: now
          }).catch(function(e) { console.warn('[banquet-sync] 自动审批日志写入失败:', e) })
        }
      }

      // Generate income from the submitted banquet purchase + service charge
      await syncIncomeFromPurchase({
        purchaseId: purchaseId,
        purchaseAmount: dishPrice,
        reservationData: docData,
        reservationId: reservationId,
        settings: settings,
        userInfo: userInfo
      })
    } else {
      if (first && first.autoGenerated) {
        await deleteIncomeByPurchase(first._id, reservationId)
        await db.deleteDoc(COLLECTIONS.PURCHASE, first._id)
      }
    }
  } catch (err) {
    console.warn('[banquet-sync] 同步宴会菜价失败:', err)
  }
}

/**
 * Generate or update income based on a banquet purchase (submitted dish price) + service charge.
 * Income amount = purchaseAmount + serviceCharge (from settings based on reservation time slot).
 *
 * This replaces the old syncIncome that derived income directly from reservation.dishPrice.
 * Income is now linked to the purchase via `purchaseId` in addition to `reservationId`.
 */
async function syncIncomeFromPurchase({ purchaseId, purchaseAmount, reservationData, reservationId, settings, userInfo }) {
  try {
    const time = (reservationData && reservationData.time) || '中午'
    const chargeNoon = Number(settings.serviceChargeNoon) || 0
    const chargeNight = Number(settings.serviceChargeNight) || 0
    const charge = time === '中午' ? chargeNoon : chargeNight
    const amount = purchaseAmount + charge

    // Find existing auto-generated income linked to this reservation (covers both
    // new purchaseId-linked records and legacy reservationId-only records)
    const existing = await db.queryAll(COLLECTIONS.INCOME, { reservationId: reservationId, autoGenerated: true })
    const hasExisting = existing.data && existing.data.length > 0
    const first = hasExisting ? existing.data[0] : null

    const incomeData = {
      type: 'dining', amount: amount,
      date: formatDate(reservationData.date),
      source: (reservationData && reservationData.customerName) || '',
      reservationId: reservationId,
      purchaseId: purchaseId,
      remark: '',
      collectedBy: (userInfo && userInfo._id) || '',
      collectedByName: (userInfo && userInfo.name) || '',
      calcMode: 'dishPrice',
      dishPrice: purchaseAmount,
      serviceCharge: charge,
      guestCount: (reservationData && reservationData.guestCount) || 0,
      standard: (reservationData && reservationData.standard) || 0,
      roomName: (reservationData && reservationData.roomName) || '',
      autoGenerated: true
    }
    if (!incomeData.collectedBy) delete incomeData.collectedBy

    if (hasExisting) {
      await db.updateDoc(COLLECTIONS.INCOME, first._id, incomeData)
    } else {
      await db.addDoc(COLLECTIONS.INCOME, incomeData)
      await db.updateDoc(COLLECTIONS.RESERVATION, reservationId, { hasIncome: true })
    }
  } catch (err) {
    console.warn('[banquet-sync] 从采购生成收入失败:', err)
  }
}

/**
 * Delete auto-generated income linked to a purchase.
 * Queries by purchaseId first, then falls back to reservationId for legacy records.
 */
async function deleteIncomeByPurchase(purchaseId, reservationId) {
  try {
    // Delete income linked by purchaseId
    var incomes = await db.queryAll(COLLECTIONS.INCOME, { purchaseId: purchaseId, autoGenerated: true })
    for (var i = 0; i < (incomes.data || []).length; i++) {
      await db.deleteDoc(COLLECTIONS.INCOME, incomes.data[i]._id)
    }
    // Fallback: delete legacy income linked only by reservationId (no purchaseId)
    if (reservationId) {
      var legacy = await db.queryAll(COLLECTIONS.INCOME, { reservationId: reservationId, autoGenerated: true })
      for (var j = 0; j < (legacy.data || []).length; j++) {
        await db.deleteDoc(COLLECTIONS.INCOME, legacy.data[j]._id)
      }
    }
  } catch (err) {
    console.warn('[banquet-sync] 删除关联收入失败:', err)
  }
}

/**
 * Delete all auto-generated purchase / income records linked to a reservation.
 * Called when the reservation itself is deleted.
 */
async function deleteBanquetPurchase(reservationId) {
  try {
    const purchases = await db.queryAll(COLLECTIONS.PURCHASE, {
      sourceReservationId: reservationId, autoGenerated: true
    })
    for (let i = 0; i < (purchases.data || []).length; i++) {
      var p = purchases.data[i]
      // Delete income linked to this purchase before deleting the purchase
      await deleteIncomeByPurchase(p._id, reservationId)
      await db.deleteDoc(COLLECTIONS.PURCHASE, p._id)
    }
  } catch (err) {
    console.warn('[banquet-sync] 删除关联记录失败:', err)
  }
}

module.exports = {
  syncBanquetPurchase,
  syncIncomeFromPurchase,
  deleteIncomeByPurchase,
  deleteBanquetPurchase,
  isNoStandardRoom
}
