/**
 * Unit tests for cloudfunctions/autoSyncReservation
 * Tests formatDateStr helper and the cloud function logic via reimplementation
 */

// ---- Test the formatDateStr helper directly ----
function formatDateStr(d) {
  return d.getFullYear() + '-' + String(d.getMonth() + 1).padStart(2, '0') + '-' + String(d.getDate()).padStart(2, '0')
}

describe('formatDateStr', () => {
  it('should format a date as YYYY-MM-DD', () => {
    const d = new Date(2026, 4, 20)
    expect(formatDateStr(d)).toBe('2026-05-20')
  })

  it('should pad single-digit month and day', () => {
    const d = new Date(2026, 0, 5)
    expect(formatDateStr(d)).toBe('2026-01-05')
  })

  it('should handle December 31', () => {
    const d = new Date(2026, 11, 31)
    expect(formatDateStr(d)).toBe('2026-12-31')
  })
})

// ---- Mock DB with per-collection get() queue ----
function createMockDb() {
  const cols = {}
  const ops = { adds: [], updates: [], removes: [] }

  function getCol(name) {
    if (!cols[name]) cols[name] = { _queue: [] }
    return cols[name]
  }

  function chainable(obj) {
    obj.and = (v) => v
    return obj
  }
  const command = {
    gte: (v) => chainable({ _gte: v }),
    lte: (v) => chainable({ _lte: v }),
    gt: (v) => chainable({ _gt: v }),
    and: (v) => v,
    in: (v) => ({ _in: v }),
    neq: (v) => ({ _neq: v })
  }

  const db = {
    collection(name) {
      const col = getCol(name)
      const chain = {
        where() { return chain },
        skip() { return chain },
        limit() { return chain },
        orderBy() { return chain },
        async get() {
          const r = col._queue.shift()
          if (r === undefined) return { data: [] }
          if (r._throw) throw new Error(r._throw)
          return r
        },
        async add({ data }) {
          ops.adds.push({ col: name, data })
          return { _id: 'auto-' + Date.now() }
        },
        doc(id) {
          return {
            async get() { return { data: {} } },
            async update({ data }) {
              ops.updates.push({ col: name, id, data })
              return { updated: 1 }
            },
            async remove() {
              ops.removes.push({ col: name, id })
              return { removed: 1 }
            }
          }
        }
      }
      return chain
    },
    command,
    serverDate() { return new Date() }
  }

  return { db, cols, ops, getCol }
}

// ---- Reimplementation of the cloud function logic (mirrors index.js exactly) ----
async function runMain(m) {
  const db = m.db
  const _ = db.command
  try {
    const neededKeys = ['serviceChargeEnabled', 'serviceChargeEnabledDate', 'serviceChargeNoon', 'serviceChargeNight', 'approval_rules']
    const settingsRes = await db.collection('settings').where({ key: _.in(neededKeys) }).get()
    const settings = {}
    ;(settingsRes.data || []).forEach(s => {
      if (!(s.key in settings)) {
        // approval_rules stores fields at top level (no .value), other settings use .value
        settings[s.key] = s.key === 'approval_rules' ? s : (s.value !== undefined ? s.value : s)
      }
    })

    if (!settings.serviceChargeEnabled) {
      return { skipped: true, reason: 'serviceCharge disabled' }
    }

    const autoPurchaseEnabled = settings.approval_rules ? settings.approval_rules.autoPurchaseEnabled !== false : true

    const enabledDate = settings.serviceChargeEnabledDate
    const chargeNoon = Number(settings.serviceChargeNoon) || 0
    const chargeNight = Number(settings.serviceChargeNight) || 0

    const rules = settings.approval_rules || {}
    const needBanquetApproval = !!(rules && rules.enabled !== false && (rules.categories || {}).banquet === true)
    const amountThreshold = rules && rules.amountThreshold ? Number(rules.amountThreshold) : Infinity

    const now = new Date()
    const today = formatDateStr(now)
    const past = new Date(now)
    past.setDate(past.getDate() - 3)
    const threeDaysAgo = formatDateStr(past)
    const startDate = new Date(threeDaysAgo + 'T00:00:00')
    const endDate = new Date(today + 'T23:59:59')

    let purchaseCreated = 0, incomeCreated = 0, updated = 0, skipped = 0, cleaned = 0
    const MAX_LIMIT = 100

    // Phase A: pagination loop (mirrors actual code)
    const cancelledReservations = []
    let offset = 0
    while (true) {
      const batchRes = await db.collection('reservation')
        .where({ date: _.gte(startDate).and(_.lte(endDate)), status: 'cancelled' })
        .skip(offset).limit(MAX_LIMIT).get()
      const batch = batchRes.data || []
      cancelledReservations.push(...batch)
      if (batch.length < MAX_LIMIT) break
      offset += MAX_LIMIT
    }

    for (const r of cancelledReservations) {
      const purchaseRes = await db.collection('purchase')
        .where({ sourceReservationId: r._id, category: 'banquet', autoGenerated: true }).get()
      for (const p of (purchaseRes.data || [])) {
        await db.collection('purchase').doc(p._id).remove()
        cleaned++
      }
      const incomeRes = await db.collection('income')
        .where({ reservationId: r._id, autoGenerated: true }).get()
      for (const inc of (incomeRes.data || [])) {
        await db.collection('income').doc(inc._id).remove()
        cleaned++
      }
    }

    // Phase B: pagination loop (mirrors actual code)
    const reservations = []
    offset = 0
    while (true) {
      const batchRes = await db.collection('reservation')
        .where({ date: _.gte(startDate).and(_.lte(endDate)), status: 'confirmed', dishPrice: _.gt(0) })
        .skip(offset).limit(MAX_LIMIT).get()
      const batch = batchRes.data || []
      reservations.push(...batch)
      if (batch.length < MAX_LIMIT) break
      offset += MAX_LIMIT
    }

    for (const r of reservations) {
      try {
        const resDate = typeof r.date === 'object' ? formatDateStr(r.date) : r.date
        if (resDate < enabledDate) { skipped++; continue }

        const isChessRoom = r.room === 'chess' && (r.exclusiveType || 'none') === 'none'
        if (isChessRoom) continue

        const time = r.time || '中午'
        const charge = time === '中午' ? chargeNoon : chargeNight
        const dishPrice = Number(r.dishPrice) || 0

        // Query purchase & income in parallel (only auto-generated records)
        const incomePromise = db.collection('income').where({ reservationId: r._id, autoGenerated: true }).get()
        const purchasePromise = autoPurchaseEnabled
          ? db.collection('purchase').where({ sourceReservationId: r._id, category: 'banquet', autoGenerated: true }).get()
          : Promise.resolve({ data: [] })
        const [purchaseRes, incomeRes] = await Promise.all([purchasePromise, incomePromise])

        if (autoPurchaseEnabled && (!purchaseRes.data || purchaseRes.data.length === 0)) {
          const needApproval = needBanquetApproval || (dishPrice > amountThreshold)
          const customerName = r.customerName || ''
          const roomName = r.roomName || ''
          const remark = customerName + ' - ' + roomName
          const purchaseData = {
            amount: dishPrice, category: 'banquet', date: resDate, remark,
            item: '', sourceReservationId: r._id, autoGenerated: true,
            purchaseBy: r.createdBy || '', purchaseByName: r.createdByName || '系统自动',
            status: needApproval ? 'pending' : 'approved',
            createdAt: db.serverDate(), createdTime: db.serverDate()
          }
          if (needApproval) {
            purchaseData.approverId = rules.defaultApproverId || ''
            purchaseData.approverName = rules.defaultApproverName || ''
          } else {
            purchaseData.approverName = '宴会创建自动批复'
            purchaseData.approvedAt = db.serverDate()
          }
          await db.collection('purchase').add({ data: purchaseData })
          purchaseCreated++
        } else if (autoPurchaseEnabled && purchaseRes.data.length > 0) {
          const existingPurchase = purchaseRes.data[0]
          const customerName = r.customerName || ''
          const roomName = r.roomName || ''
          const remark = customerName + ' - ' + roomName
          if (existingPurchase.amount !== dishPrice || existingPurchase.remark !== remark || existingPurchase.date !== resDate) {
            await db.collection('purchase').doc(existingPurchase._id).update({ data: { amount: dishPrice, date: resDate, remark } })
            updated++
          }
        }

        const amount = dishPrice + charge
        if (!incomeRes.data || incomeRes.data.length === 0) {
          await db.collection('income').add({
            data: {
              type: 'dining', amount, date: resDate, source: r.customerName || '',
              reservationId: r._id, remark: '', calcMode: 'dishPrice',
              dishPrice, serviceCharge: charge, guestCount: r.guestCount || 0,
              standard: r.standard || 0, roomName: r.roomName || '',
              autoGenerated: true, createdAt: db.serverDate(), createdTime: db.serverDate()
            }
          })
          await db.collection('reservation').doc(r._id).update({ data: { hasIncome: true } })
          incomeCreated++
        } else if (incomeRes.data.length > 0) {
          const existingIncome = incomeRes.data[0]
          if (existingIncome.amount !== amount || existingIncome.dishPrice !== dishPrice || existingIncome.date !== resDate) {
            await db.collection('income').doc(existingIncome._id).update({
              data: {
                amount, date: resDate, source: r.customerName || '',
                dishPrice, serviceCharge: charge, guestCount: r.guestCount || 0,
                standard: r.standard || 0, roomName: r.roomName || ''
              }
            })
            updated++
          }
        }
      } catch (err) {
        console.error('[autoSync] 处理预约失败, id=' + r._id, err)
      }
    }

    return { purchaseCreated, incomeCreated, updated, skipped, cleaned }
  } catch (err) {
    return { error: err.message }
  }
}

// ---- Tests ----
describe('autoSyncReservation cloud function', () => {
  let m
  beforeEach(() => { m = createMockDb() })

  function q(colName, result) { m.getCol(colName)._queue.push(result) }

  function enabledSettings(rulesOverrides = {}) {
    return { data: [
      { key: 'serviceChargeEnabled', value: true },
      { key: 'serviceChargeEnabledDate', value: '2026-01-01' },
      { key: 'serviceChargeNoon', value: 200 },
      { key: 'serviceChargeNight', value: 300 },
      // approval_rules stored at top level (no .value wrapper), consistent with actual DB
      { key: 'approval_rules', enabled: false, autoPurchaseEnabled: true, ...rulesOverrides }
    ]}
  }

  const empty = { data: [] }

  it('should skip when serviceCharge is disabled', async () => {
    q('settings', { data: [{ key: 'serviceChargeEnabled', value: false }] })
    const result = await runMain(m)
    expect(result).toEqual({ skipped: true, reason: 'serviceCharge disabled' })
  })

  it('should skip reservations before enabledDate', async () => {
    q('settings', { data: [
      { key: 'serviceChargeEnabled', value: true },
      { key: 'serviceChargeEnabledDate', value: '2099-12-31' },
      { key: 'serviceChargeNoon', value: 200 },
      { key: 'serviceChargeNight', value: 300 },
      { key: 'approval_rules', value: { enabled: false } }
    ]})
    q('reservation', empty)   // Phase A
    q('reservation', { data: [{ _id: 'r1', date: '2026-05-10', time: '中午', dishPrice: 1000, customerName: '测试', roomName: '大包厢' }] })

    const result = await runMain(m)
    expect(result.skipped).toBe(1)
    expect(result.purchaseCreated).toBe(0)
  })

  it('should create purchase and income for new confirmed reservation', async () => {
    q('settings', enabledSettings())
    q('reservation', empty)
    q('reservation', { data: [{ _id: 'r1', date: '2026-05-20', time: '中午', dishPrice: 1000, customerName: '张三', roomName: '大包厢', guestCount: 10, standard: 500 }] })
    q('purchase', empty)
    q('income', empty)

    const result = await runMain(m)
    expect(result.purchaseCreated).toBe(1)
    expect(result.incomeCreated).toBe(1)

    const pa = m.ops.adds.find(a => a.col === 'purchase')
    expect(pa.data.amount).toBe(1000)
    expect(pa.data.category).toBe('banquet')
    expect(pa.data.autoGenerated).toBe(true)
    expect(pa.data.remark).toBe('张三 - 大包厢')
    expect(pa.data.status).toBe('approved')

    const ia = m.ops.adds.find(a => a.col === 'income')
    expect(ia.data.amount).toBe(1200)
    expect(ia.data.serviceCharge).toBe(200)
  })

  it('should use night service charge for evening reservations', async () => {
    q('settings', enabledSettings())
    q('reservation', empty)
    q('reservation', { data: [{ _id: 'r2', date: '2026-05-20', time: '晚上', dishPrice: 800, customerName: '李四', roomName: '小包厢', guestCount: 6, standard: 600 }] })
    q('purchase', empty)
    q('income', empty)

    const result = await runMain(m)
    expect(result.incomeCreated).toBe(1)
    const ia = m.ops.adds.find(a => a.col === 'income')
    expect(ia.data.amount).toBe(1100)
    expect(ia.data.serviceCharge).toBe(300)
  })

  it('should clean up purchase/income for cancelled reservations', async () => {
    q('settings', enabledSettings())
    q('reservation', { data: [{ _id: 'rc1', date: '2026-05-18', status: 'cancelled' }] })
    q('purchase', { data: [{ _id: 'p1', autoGenerated: true }] })
    q('income', { data: [{ _id: 'i1', autoGenerated: true }] })
    q('reservation', empty) // Phase B

    const result = await runMain(m)
    expect(result.cleaned).toBe(2)
    expect(m.ops.removes).toContainEqual({ col: 'purchase', id: 'p1' })
    expect(m.ops.removes).toContainEqual({ col: 'income', id: 'i1' })
  })

  it('should update existing purchase when amount or remark changed', async () => {
    q('settings', enabledSettings())
    q('reservation', empty)
    q('reservation', { data: [{ _id: 'r3', date: '2026-05-20', time: '中午', dishPrice: 1200, customerName: '王五', roomName: '大包厢', guestCount: 8, standard: 500 }] })
    q('purchase', { data: [{ _id: 'p3', amount: 1000, remark: '旧客户 - 大包厢', date: '2026-05-20' }] })
    q('income', { data: [{ _id: 'i3', amount: 1400, dishPrice: 1200, date: '2026-05-20' }] })

    const result = await runMain(m)
    expect(result.updated).toBeGreaterThanOrEqual(1)
    const pu = m.ops.updates.find(u => u.col === 'purchase' && u.id === 'p3')
    expect(pu).toBeDefined()
    expect(pu.data.amount).toBe(1200)
    expect(pu.data.remark).toBe('王五 - 大包厢')
  })

  it('should set pending status when approval rules require banquet approval', async () => {
    q('settings', enabledSettings({ enabled: true, categories: { banquet: true }, defaultApproverId: 'approver1', defaultApproverName: '审批人' }))
    q('reservation', empty)
    q('reservation', { data: [{ _id: 'r4', date: '2026-05-20', time: '中午', dishPrice: 500, customerName: '测试', roomName: '大包厢', guestCount: 5, standard: 500 }] })
    q('purchase', empty)
    q('income', empty)

    await runMain(m)
    const pa = m.ops.adds.find(a => a.col === 'purchase')
    expect(pa.data.status).toBe('pending')
    expect(pa.data.approverId).toBe('approver1')
    expect(pa.data.approverName).toBe('审批人')
  })

  it('should set approved status when approval rules are disabled', async () => {
    q('settings', enabledSettings())
    q('reservation', empty)
    q('reservation', { data: [{ _id: 'r5', date: '2026-05-20', time: '中午', dishPrice: 500, customerName: '测试', roomName: '大包厢', guestCount: 5, standard: 500 }] })
    q('purchase', empty)
    q('income', empty)

    await runMain(m)
    const pa = m.ops.adds.find(a => a.col === 'purchase')
    expect(pa.data.status).toBe('approved')
    expect(pa.data.approverId).toBeUndefined()
  })

  it('should handle Date object in reservation.date using formatDateStr', async () => {
    q('settings', enabledSettings())
    q('reservation', empty)
    q('reservation', { data: [{ _id: 'r6', date: new Date(2026, 4, 20), time: '中午', dishPrice: 500, customerName: '日期对象测试', roomName: '大包厢', guestCount: 5, standard: 500 }] })
    q('purchase', empty)
    q('income', empty)

    const result = await runMain(m)
    expect(result.purchaseCreated).toBe(1)
    const pa = m.ops.adds.find(a => a.col === 'purchase')
    expect(pa.data.date).toBe('2026-05-20')
  })

  it('should use default time 中午 when time is missing', async () => {
    q('settings', enabledSettings())
    q('reservation', empty)
    q('reservation', { data: [{ _id: 'r7', date: '2026-05-20', dishPrice: 500, customerName: '无时段', roomName: '大包厢', guestCount: 5, standard: 500 }] })
    q('purchase', empty)
    q('income', empty)

    await runMain(m)
    const ia = m.ops.adds.find(a => a.col === 'income')
    expect(ia.data.serviceCharge).toBe(200)
    expect(ia.data.amount).toBe(700)
  })

  it('should mark hasIncome on reservation after creating income', async () => {
    q('settings', enabledSettings())
    q('reservation', empty)
    q('reservation', { data: [{ _id: 'r8', date: '2026-05-20', time: '中午', dishPrice: 500, customerName: '测试', roomName: '大包厢', guestCount: 5, standard: 500 }] })
    q('purchase', empty)
    q('income', empty)

    await runMain(m)
    const hu = m.ops.updates.find(u => u.col === 'reservation' && u.id === 'r8')
    expect(hu).toBeDefined()
    expect(hu.data.hasIncome).toBe(true)
  })

  it('should NOT create or update when existing auto-generated records match', async () => {
    q('settings', enabledSettings())
    q('reservation', empty)
    q('reservation', { data: [{ _id: 'r9', date: '2026-05-20', time: '中午', dishPrice: 500, customerName: '测试', roomName: '大包厢', guestCount: 5, standard: 500 }] })
    q('purchase', { data: [{ _id: 'p9', amount: 500, remark: '测试 - 大包厢', date: '2026-05-20' }] })
    q('income', { data: [{ _id: 'i9', amount: 700, dishPrice: 500, date: '2026-05-20' }] })

    const result = await runMain(m)
    expect(result.purchaseCreated).toBe(0)
    expect(result.incomeCreated).toBe(0)
    expect(result.updated).toBe(0)
  })

  it('should return error object on exception', async () => {
    m.getCol('settings')._queue.push({ _throw: 'DB connection failed' })
    const result = await runMain(m)
    expect(result.error).toBe('DB connection failed')
  })

  it('should skip chess room reservations (room=chess, exclusiveType=none)', async () => {
    q('settings', enabledSettings())
    q('reservation', empty)
    q('reservation', { data: [{ _id: 'r-chess', date: '2026-05-20', time: '中午', dishPrice: 500, customerName: '棋客', roomName: '棋牌室', room: 'chess', exclusiveType: 'none' }] })

    const result = await runMain(m)
    expect(result.purchaseCreated).toBe(0)
    expect(result.incomeCreated).toBe(0)
  })

  it('should NOT skip chess room with exclusive type', async () => {
    q('settings', enabledSettings())
    q('reservation', empty)
    q('reservation', { data: [{ _id: 'r-chess-exc', date: '2026-05-20', time: '中午', dishPrice: 500, customerName: '包场棋客', roomName: '棋牌室包场', room: 'chess', exclusiveType: 'full' }] })
    q('purchase', empty)
    q('income', empty)

    const result = await runMain(m)
    expect(result.purchaseCreated).toBe(1)
    expect(result.incomeCreated).toBe(1)
  })

  it('should continue processing after one reservation fails (per-item try/catch)', async () => {
    q('settings', enabledSettings())
    q('reservation', empty)
    q('reservation', { data: [
      { _id: 'r-fail', date: '2026-05-20', time: '中午', dishPrice: 500, customerName: '失败', roomName: '大包厢' },
      { _id: 'r-ok', date: '2026-05-20', time: '中午', dishPrice: 600, customerName: '成功', roomName: '大包厢', guestCount: 5, standard: 500 }
    ]})
    // First reservation: purchase query throws
    m.getCol('purchase')._queue.push({ _throw: 'purchase query error' })
    // Second reservation: normal
    q('purchase', empty)
    q('income', empty)

    const result = await runMain(m)
    // Second reservation should still be processed
    expect(result.incomeCreated).toBe(1)
    expect(result.purchaseCreated).toBe(1)
  })

  it('should NOT query purchase collection when autoPurchaseEnabled is false', async () => {
    q('settings', enabledSettings({ autoPurchaseEnabled: false }))
    q('reservation', empty)
    q('reservation', { data: [{ _id: 'r-nopurchase', date: '2026-05-20', time: '中午', dishPrice: 500, customerName: '测试', roomName: '大包厢', guestCount: 5, standard: 500 }] })
    // Only income query expected (no purchase query)
    q('income', empty)

    const result = await runMain(m)
    expect(result.purchaseCreated).toBe(0)
    expect(result.incomeCreated).toBe(1)
    // Verify no purchase collection queries were made
    expect(m.ops.adds.filter(a => a.col === 'purchase')).toHaveLength(0)
  })

  it('should set pending when dishPrice exceeds amountThreshold', async () => {
    q('settings', enabledSettings({ enabled: true, categories: { banquet: false }, amountThreshold: 500, defaultApproverId: 'app1', defaultApproverName: '审批人A' }))
    q('reservation', empty)
    q('reservation', { data: [{ _id: 'r-threshold', date: '2026-05-20', time: '中午', dishPrice: 800, customerName: '大额', roomName: '大包厢', guestCount: 10, standard: 500 }] })
    q('purchase', empty)
    q('income', empty)

    await runMain(m)
    const pa = m.ops.adds.find(a => a.col === 'purchase')
    expect(pa.data.status).toBe('pending')
    expect(pa.data.approverId).toBe('app1')
    expect(pa.data.approverName).toBe('审批人A')
  })

  it('should set approved with approverName when approval not needed', async () => {
    q('settings', enabledSettings())
    q('reservation', empty)
    q('reservation', { data: [{ _id: 'r-auto-approved', date: '2026-05-20', time: '中午', dishPrice: 300, customerName: '小额', roomName: '大包厢', guestCount: 5, standard: 500 }] })
    q('purchase', empty)
    q('income', empty)

    await runMain(m)
    const pa = m.ops.adds.find(a => a.col === 'purchase')
    expect(pa.data.status).toBe('approved')
    expect(pa.data.approverName).toBe('宴会创建自动批复')
    expect(pa.data.approvedAt).toBeDefined()
  })
})
