/**
 * Unit tests for reservation-add/helpers/sync.js
 *
 * Tests the pure helper functions:
 *   - isNoStandardRoom
 *   - syncBanquetPurchase
 *   - syncIncomeFromPurchase
 *   - deleteIncomeByPurchase
 *   - deleteBanquetPurchase
 */

const mockQueryAll = jest.fn()
const mockAddDoc = jest.fn()
const mockUpdateDoc = jest.fn()
const mockDeleteDoc = jest.fn()

jest.mock('../../miniprogram/utils/db', () => ({
  queryAll: mockQueryAll,
  addDoc: mockAddDoc,
  updateDoc: mockUpdateDoc,
  deleteDoc: mockDeleteDoc,
  COLLECTIONS: {
    SETTINGS: 'settings',
    RESERVATION: 'reservation',
    PURCHASE: 'purchase',
    INCOME: 'income',
    APPROVAL_LOG: 'approval_log'
  }
}))

const { COLLECTIONS } = require('../../miniprogram/utils/db')

jest.mock('../../miniprogram/utils/helpers', () => ({
  formatDate: jest.fn((d) => {
    if (!d) return ''
    const date = d instanceof Date ? d : new Date(d)
    if (isNaN(date.getTime())) return ''
    return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`
  })
}))

const {
  isNoStandardRoom,
  syncBanquetPurchase,
  syncIncomeFromPurchase,
  deleteIncomeByPurchase,
  deleteBanquetPurchase
} = require('../../miniprogram/pages/reservation-add/helpers/sync')

describe('sync helpers: isNoStandardRoom', () => {
  test('returns true when standards is empty and exclusiveType is none', () => {
    expect(isNoStandardRoom({ standards: [] }, 'none')).toBe(true)
  })

  test('returns false when standards is non-empty and exclusiveType is none', () => {
    expect(isNoStandardRoom({ standards: [500] }, 'none')).toBe(false)
  })

  test('returns false when standards is empty but exclusiveType is not none', () => {
    expect(isNoStandardRoom({ standards: [] }, 'full')).toBe(false)
  })

  test('returns false when roomConfig is null', () => {
    expect(isNoStandardRoom(null, 'none')).toBe(false)
  })

  test('returns false when roomConfig is undefined', () => {
    expect(isNoStandardRoom(undefined, 'none')).toBe(false)
  })

  test('returns true when standards is missing (defaults to empty)', () => {
    expect(isNoStandardRoom({}, 'none')).toBe(true)
  })
})

describe('sync helpers: syncBanquetPurchase', () => {
  beforeEach(() => {
    jest.clearAllMocks()
    // Default mocks: income queries return empty (no existing income)
    mockQueryAll.mockResolvedValue({ data: [] })
    mockAddDoc.mockResolvedValue({ _id: 'auto-id' })
    mockUpdateDoc.mockResolvedValue({ updated: 1 })
    mockDeleteDoc.mockResolvedValue({ removed: 1 })
  })

  const defaultRoomConfig = { id: 'big', standards: [500, 600, 800] }
  const defaultUserInfo = { _id: 'u1', name: '测试用户' }
  const defaultSettings = { approval_rules: { enabled: false, autoPurchaseEnabled: true } }

  test('skips for no-standard room with exclusiveType=none', async () => {
    const roomConfig = { id: 'chess', standards: [] }
    await syncBanquetPurchase({
      docData: { dishPrice: 500, exclusiveType: 'none' },
      reservationId: 'r1',
      isCreate: true,
      roomConfig,
      settings: defaultSettings,
      userInfo: defaultUserInfo
    })
    expect(mockQueryAll).not.toHaveBeenCalled()
  })

  test('does NOT skip for no-standard room when exclusiveType is not none', async () => {
    const roomConfig = { id: 'chess', standards: [] }
    mockQueryAll.mockResolvedValueOnce({ data: [] })
    mockAddDoc.mockResolvedValueOnce({ _id: 'p1' })

    await syncBanquetPurchase({
      docData: { dishPrice: 500, exclusiveType: 'full', customerName: '张三', roomName: '棋牌室' },
      reservationId: 'r1',
      isCreate: true,
      roomConfig,
      settings: defaultSettings,
      userInfo: defaultUserInfo
    })
    expect(mockQueryAll).toHaveBeenCalled()
  })

  test('creates purchase with approved status when no approval rules', async () => {
    mockQueryAll.mockResolvedValueOnce({ data: [] })
    mockAddDoc.mockResolvedValueOnce({ _id: 'p1' })

    await syncBanquetPurchase({
      docData: { dishPrice: 1000, exclusiveType: 'none', customerName: '张三', roomName: '大包厢' },
      reservationId: 'r1',
      isCreate: true,
      roomConfig: defaultRoomConfig,
      settings: defaultSettings,
      userInfo: defaultUserInfo
    })

    expect(mockAddDoc).toHaveBeenCalledWith(COLLECTIONS.PURCHASE, expect.objectContaining({
      amount: 1000,
      category: 'banquet',
      sourceReservationId: 'r1',
      autoGenerated: true,
      status: 'approved',
      approverName: '宴会创建自动批复'
    }))
  })

  test('creates purchase with pending status when banquet approval is required', async () => {
    mockQueryAll.mockResolvedValueOnce({ data: [] })
    mockAddDoc.mockResolvedValueOnce({ _id: 'p2' })

    const settings = {
      approval_rules: {
        enabled: true,
        categories: { banquet: true },
        defaultApproverId: 'a1',
        defaultApproverName: '审批人'
      }
    }

    await syncBanquetPurchase({
      docData: { dishPrice: 500, exclusiveType: 'none', customerName: '需审批', roomName: '大包厢' },
      reservationId: 'r2',
      isCreate: true,
      roomConfig: defaultRoomConfig,
      settings,
      userInfo: defaultUserInfo
    })

    expect(mockAddDoc).toHaveBeenCalledWith(COLLECTIONS.PURCHASE, expect.objectContaining({
      status: 'pending',
      approverId: 'a1',
      approverName: '审批人'
    }))
  })

  test('creates pending purchase when dishPrice exceeds amountThreshold', async () => {
    mockQueryAll.mockResolvedValueOnce({ data: [] })
    mockAddDoc.mockResolvedValueOnce({ _id: 'p3' })

    const settings = {
      approval_rules: {
        enabled: true,
        categories: { banquet: false },
        amountThreshold: 500,
        defaultApproverId: 'a2',
        defaultApproverName: '大额审批'
      }
    }

    await syncBanquetPurchase({
      docData: { dishPrice: 800, exclusiveType: 'none', customerName: '大额', roomName: '大包厢' },
      reservationId: 'r3',
      isCreate: true,
      roomConfig: defaultRoomConfig,
      settings,
      userInfo: defaultUserInfo
    })

    expect(mockAddDoc).toHaveBeenCalledWith(COLLECTIONS.PURCHASE, expect.objectContaining({
      status: 'pending',
      amount: 800
    }))
  })

  test('writes approval log when auto-approved on create', async () => {
    mockQueryAll.mockResolvedValueOnce({ data: [] })
    mockAddDoc.mockResolvedValueOnce({ _id: 'p-auto' })

    await syncBanquetPurchase({
      docData: { dishPrice: 300, exclusiveType: 'none', customerName: '自动', roomName: '大包厢' },
      reservationId: 'r4',
      isCreate: true,
      roomConfig: defaultRoomConfig,
      settings: defaultSettings,
      userInfo: defaultUserInfo
    })

    expect(mockAddDoc).toHaveBeenCalledWith(COLLECTIONS.APPROVAL_LOG, expect.objectContaining({
      purchaseId: 'p-auto',
      action: 'approved',
      operatorName: '宴会创建自动批复'
    }))
  })

  test('does NOT write approval log when approval is pending', async () => {
    mockQueryAll.mockResolvedValueOnce({ data: [] })
    mockAddDoc.mockResolvedValueOnce({ _id: 'p-pending' })

    const settings = {
      approval_rules: { enabled: true, categories: { banquet: true }, defaultApproverId: 'a1', defaultApproverName: '审批人' }
    }

    await syncBanquetPurchase({
      docData: { dishPrice: 500, exclusiveType: 'none', customerName: '需审批', roomName: '大包厢' },
      reservationId: 'r5',
      isCreate: true,
      roomConfig: defaultRoomConfig,
      settings,
      userInfo: defaultUserInfo
    })

    const approvalLogCalls = mockAddDoc.mock.calls.filter(c => c[0] === COLLECTIONS.APPROVAL_LOG)
    expect(approvalLogCalls.length).toBe(0)
  })

  test('updates existing purchase on edit (isCreate=false)', async () => {
    mockQueryAll.mockResolvedValueOnce({ data: [{ _id: 'p1', autoGenerated: true }] })
    mockUpdateDoc.mockResolvedValueOnce({ updated: 1 })

    await syncBanquetPurchase({
      docData: { dishPrice: 1200, exclusiveType: 'none', customerName: '张三', roomName: '大包厢' },
      reservationId: 'r1',
      isCreate: false,
      roomConfig: defaultRoomConfig,
      settings: defaultSettings,
      userInfo: defaultUserInfo
    })

    expect(mockUpdateDoc).toHaveBeenCalledWith(COLLECTIONS.PURCHASE, 'p1', expect.objectContaining({
      amount: 1200
    }))
  })

  test('does NOT update existing purchase when isCreate=true', async () => {
    mockQueryAll.mockResolvedValueOnce({ data: [{ _id: 'p1', autoGenerated: true }] })

    await syncBanquetPurchase({
      docData: { dishPrice: 1000, exclusiveType: 'none', customerName: '张三', roomName: '大包厢', time: '中午', date: new Date('2099-06-01') },
      reservationId: 'r1',
      isCreate: true,
      roomConfig: defaultRoomConfig,
      settings: { ...defaultSettings, serviceChargeNoon: 200, serviceChargeNight: 300 },
      userInfo: defaultUserInfo
    })

    // syncBanquetPurchase should NOT update the purchase (isCreate=true),
    // but syncIncomeFromPurchase may still update RESERVATION (hasIncome)
    const purchaseUpdateCalls = mockUpdateDoc.mock.calls.filter(c => c[0] === COLLECTIONS.PURCHASE)
    expect(purchaseUpdateCalls.length).toBe(0)
  })

  test('deletes autoGenerated purchase when dishPrice is 0', async () => {
    mockQueryAll.mockResolvedValueOnce({ data: [{ _id: 'p1', autoGenerated: true }] })
    mockDeleteDoc.mockResolvedValueOnce({ removed: 1 })

    await syncBanquetPurchase({
      docData: { dishPrice: 0, exclusiveType: 'none', customerName: '张三', roomName: '大包厢' },
      reservationId: 'r1',
      isCreate: false,
      roomConfig: defaultRoomConfig,
      settings: defaultSettings,
      userInfo: defaultUserInfo
    })

    expect(mockDeleteDoc).toHaveBeenCalledWith(COLLECTIONS.PURCHASE, 'p1')
  })

  test('does NOT delete non-autoGenerated purchase when dishPrice is 0', async () => {
    mockQueryAll.mockResolvedValueOnce({ data: [{ _id: 'p1', autoGenerated: false }] })

    await syncBanquetPurchase({
      docData: { dishPrice: 0, exclusiveType: 'none', customerName: '张三', roomName: '大包厢' },
      reservationId: 'r1',
      isCreate: false,
      roomConfig: defaultRoomConfig,
      settings: defaultSettings,
      userInfo: defaultUserInfo
    })

    expect(mockDeleteDoc).not.toHaveBeenCalled()
  })

  test('swallows errors silently', async () => {
    mockQueryAll.mockRejectedValueOnce(new Error('network failure'))

    // Should not throw
    await syncBanquetPurchase({
      docData: { dishPrice: 500, exclusiveType: 'none', customerName: '张三', roomName: '大包厢' },
      reservationId: 'r1',
      isCreate: true,
      roomConfig: defaultRoomConfig,
      settings: defaultSettings,
      userInfo: defaultUserInfo
    })
  })
})

describe('sync helpers: syncIncomeFromPurchase', () => {
  beforeEach(() => {
    jest.clearAllMocks()
    mockQueryAll.mockResolvedValue({ data: [] })
    mockAddDoc.mockResolvedValue({ _id: 'i1' })
    mockUpdateDoc.mockResolvedValue({ updated: 1 })
  })

  const defaultUserInfo = { _id: 'u1', name: '测试用户' }

  test('creates income with noon service charge from purchase amount', async () => {
    mockQueryAll.mockResolvedValueOnce({ data: [] })

    await syncIncomeFromPurchase({
      purchaseId: 'p1',
      purchaseAmount: 1000,
      reservationData: { customerName: '张三', roomName: '大包厢', time: '中午', guestCount: 10, standard: 500, date: new Date('2099-06-01') },
      reservationId: 'r1',
      settings: { serviceChargeNoon: 200, serviceChargeNight: 300 },
      userInfo: defaultUserInfo
    })

    expect(mockAddDoc).toHaveBeenCalledWith(COLLECTIONS.INCOME, expect.objectContaining({
      amount: 1200,
      dishPrice: 1000,
      serviceCharge: 200,
      autoGenerated: true,
      reservationId: 'r1',
      purchaseId: 'p1'
    }))
    expect(mockUpdateDoc).toHaveBeenCalledWith(COLLECTIONS.RESERVATION, 'r1', { hasIncome: true })
  })

  test('creates income with night service charge', async () => {
    mockQueryAll.mockResolvedValueOnce({ data: [] })

    await syncIncomeFromPurchase({
      purchaseId: 'p2',
      purchaseAmount: 800,
      reservationData: { customerName: '李四', roomName: '小包厢', time: '晚上', guestCount: 6, standard: 600, date: new Date('2099-06-01') },
      reservationId: 'r2',
      settings: { serviceChargeNoon: 200, serviceChargeNight: 300 },
      userInfo: defaultUserInfo
    })

    expect(mockAddDoc).toHaveBeenCalledWith(COLLECTIONS.INCOME, expect.objectContaining({
      amount: 1100,
      serviceCharge: 300
    }))
  })

  test('updates existing income when found', async () => {
    mockQueryAll.mockResolvedValueOnce({ data: [{ _id: 'i1', autoGenerated: true }] })

    await syncIncomeFromPurchase({
      purchaseId: 'p1',
      purchaseAmount: 1000,
      reservationData: { customerName: '张三', roomName: '大包厢', time: '中午', guestCount: 10, standard: 500, date: new Date('2099-06-01') },
      reservationId: 'r1',
      settings: { serviceChargeNoon: 200, serviceChargeNight: 300 },
      userInfo: defaultUserInfo
    })

    expect(mockUpdateDoc).toHaveBeenCalledWith(COLLECTIONS.INCOME, 'i1', expect.objectContaining({ amount: 1200, purchaseId: 'p1' }))
    expect(mockAddDoc).not.toHaveBeenCalled()
  })

  test('defaults to noon time when reservationData has no time', async () => {
    mockQueryAll.mockResolvedValueOnce({ data: [] })

    await syncIncomeFromPurchase({
      purchaseId: 'p1',
      purchaseAmount: 500,
      reservationData: { customerName: '测试', date: new Date('2099-06-01') },
      reservationId: 'r1',
      settings: { serviceChargeNoon: 200, serviceChargeNight: 300 },
      userInfo: defaultUserInfo
    })

    expect(mockAddDoc).toHaveBeenCalledWith(COLLECTIONS.INCOME, expect.objectContaining({
      serviceCharge: 200,
      amount: 700
    }))
  })

  test('swallows errors silently', async () => {
    mockQueryAll.mockRejectedValueOnce(new Error('db error'))

    await syncIncomeFromPurchase({
      purchaseId: 'p1',
      purchaseAmount: 500,
      reservationData: { date: new Date('2099-06-01') },
      reservationId: 'r1',
      settings: {},
      userInfo: defaultUserInfo
    })
  })
})

describe('sync helpers: deleteIncomeByPurchase', () => {
  beforeEach(() => {
    jest.clearAllMocks()
    mockQueryAll.mockResolvedValue({ data: [] })
    mockDeleteDoc.mockResolvedValue({ removed: 1 })
  })

  test('deletes income linked by purchaseId', async () => {
    mockQueryAll
      .mockResolvedValueOnce({ data: [{ _id: 'i1' }] })  // by purchaseId
      // fallback by reservationId returns default empty

    await deleteIncomeByPurchase('p1', 'r1')

    expect(mockQueryAll).toHaveBeenCalledWith(COLLECTIONS.INCOME, { purchaseId: 'p1', autoGenerated: true })
    expect(mockDeleteDoc).toHaveBeenCalledWith(COLLECTIONS.INCOME, 'i1')
  })

  test('deletes legacy income linked by reservationId', async () => {
    mockQueryAll
      .mockResolvedValueOnce({ data: [] })                // by purchaseId: none
      .mockResolvedValueOnce({ data: [{ _id: 'i2' }] })   // by reservationId: found

    await deleteIncomeByPurchase('p1', 'r1')

    expect(mockQueryAll).toHaveBeenCalledWith(COLLECTIONS.INCOME, { reservationId: 'r1', autoGenerated: true })
    expect(mockDeleteDoc).toHaveBeenCalledWith(COLLECTIONS.INCOME, 'i2')
  })

  test('handles empty results without errors', async () => {
    await deleteIncomeByPurchase('p1', 'r1')

    expect(mockDeleteDoc).not.toHaveBeenCalled()
  })

  test('swallows errors silently', async () => {
    mockQueryAll.mockRejectedValueOnce(new Error('db error'))

    await deleteIncomeByPurchase('p1', 'r1')
  })
})

describe('sync helpers: deleteBanquetPurchase', () => {
  beforeEach(() => {
    jest.clearAllMocks()
    // Default: income queries return empty (no linked income)
    mockQueryAll.mockResolvedValue({ data: [] })
    mockDeleteDoc.mockResolvedValue({ removed: 1 })
  })

  test('deletes autoGenerated purchases and linked income', async () => {
    mockQueryAll
      .mockResolvedValueOnce({ data: [{ _id: 'p1' }, { _id: 'p2' }] })  // purchases
    // Income queries for p1 and p2 return default empty

    await deleteBanquetPurchase('r1')

    expect(mockQueryAll).toHaveBeenCalledWith(COLLECTIONS.PURCHASE, { sourceReservationId: 'r1', autoGenerated: true })
    expect(mockDeleteDoc).toHaveBeenCalledWith(COLLECTIONS.PURCHASE, 'p1')
    expect(mockDeleteDoc).toHaveBeenCalledWith(COLLECTIONS.PURCHASE, 'p2')
  })

  test('deletes income linked to each purchase before deleting purchase', async () => {
    mockQueryAll
      .mockResolvedValueOnce({ data: [{ _id: 'p1', autoGenerated: true }] })  // purchases
      .mockResolvedValueOnce({ data: [{ _id: 'i1' }] })  // income by purchaseId p1
    // fallback income query by reservationId returns default empty

    await deleteBanquetPurchase('r1')

    expect(mockQueryAll).toHaveBeenCalledWith(COLLECTIONS.INCOME, { purchaseId: 'p1', autoGenerated: true })
    expect(mockDeleteDoc).toHaveBeenCalledWith(COLLECTIONS.INCOME, 'i1')
    expect(mockDeleteDoc).toHaveBeenCalledWith(COLLECTIONS.PURCHASE, 'p1')
  })

  test('handles empty results', async () => {
    mockQueryAll.mockResolvedValueOnce({ data: [] })

    await deleteBanquetPurchase('r1')

    expect(mockDeleteDoc).not.toHaveBeenCalled()
  })

  test('swallows errors silently', async () => {
    mockQueryAll.mockRejectedValueOnce(new Error('db error'))

    await deleteBanquetPurchase('r1')
  })
})
